name: Archive Expired Tasks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run archive script
        run: npx tsx scripts/archiveTasks.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
