name: Auto Archive Tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  archive-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - run: NODE_ENV=production npx tsx scripts/archiveTasks.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
